name: Laravel-Test

on: [push]

jobs:
  laravel-tests:
    name: laravel phpunit test
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./src
  
    services:
      mysql:
        image: mysql:8.0.19
        ports:
          - 3306:3306
        options: --health-cmd "mysqladmin ping -h localhost" --health-interval 20s --health-timeout 10s --health-retries 10
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: db_testing

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.0'
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: composer install --no-ansi --no-interaction --no-progress --prefer-dist
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_HOST: 127.0.0.1
        DB_USERNAME: root
        DB_PASSWORD: root
      run: vendor/bin/phpunit
