name: Workflow_dispatch-Test

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'タグ名'
        required: true

jobs:
  workflow_dispatch-job:
    runs-on: ubuntu-latest
    steps:
      - name: echo Step
        run: |
          echo ${{ github.event.inputs.tag_name }}
